FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 make g++ sqlite3 libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install --build-from-source

COPY . .

EXPOSE 3001

CMD ["node", "src/index.js"]
